### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker#11]
Add some way to check and make sure each process completes, and if it doesn't, notify us of the error.

**Comment by mattretzer** [comment]
Updated all deploy.bat files to update a process log on success of each process, and spawn separate process on initiation of conversion to wait 10 minutes and check process log for any fails. This is via processwatch.ps1, which sends an alert on fail and generates an Alert textfile in root of the project for user.  Tested on nyautomation01 today for all deploy.bats, works
