### ISSUE TITLE
period in file name causes doctodocx.py to fail

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/bookmaker#127]
Sample file: https://www.dropbox.com/s/bl9gr26e3r2jyk6/INCENDIARY.Final%20for%20Composition.REVISED.doc?dl=0

Error logs from that file: 
[INCENDIARY.FinalforComposition.REVISED_9781250048943_DONE_187-stdout-and-err.txt](https://github.com/macmillanpublishers/bookmaker/files/490589/INCENDIARY.FinalforComposition.REVISED_9781250048943_DONE_187-stdout-and-err.txt)

**Comment by mattretzer** [comment]
Resolved as per: https://github.com/macmillanpublishers/bookmaker/pull/129
