### ISSUE TITLE
New break style: Space Break - Internal (int)

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/bookmaker#139]
Add handling for new line-break style: `Space Break - Internal (int)`
Should be allowed inside other sections (e.g., copyright page, dedication, epigraph, extracts)

**Comment by MacmillanWorkflows** [comment]
➤ Nellie McKesson commented:
Duplicating display of regular SpaceBreak para in PDF and EPUB, but setting it so it won't break up blockquotes, etc.
