### ISSUE TITLE
Add JSON log info to README

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker#152]
Write up how the JSON logging works in the readme.md file

**Comment by mattretzer** [comment]
@nelliemckesson :  Should I add the same content that I come up with for the bookmaker README to READMEs for any other repos using the json logging, or add a link back to an anchor for jsonlogging on the bookmaker repo README or something?

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
Added some high level info to the readme, awaiting review:  https://github.com/macmillanpublishers/bookmaker/blob/jsonlog/README.md

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
Approved and deployed.
