### ISSUE TITLE
[js] Insert cover placeholder via javascript - epubmaker.rb

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker#159]
In the secondHTMLEdit method in epubmaker, add the cover figure via javascript instead.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
PR is here: https://github.com/macmillanpublishers/bookmaker/pull/160

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
merged & tested!
