### ISSUE TITLE
[ss] Adjust chap number handling

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker#164]
Review and adjust the chapter number handling as needed: currently chap num paragraphs are removed and auto-numbering is used.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

We will be handling this the same way we currently are in the xsl (https://github.com/macmillanpublishers/bookmaker/blob/master/core/htmlmaker/wordtohtml.xsl#L494-L513), but adding a comment after the header detailing what we are doing for future readers of our html.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

sent Nellie an email re: this - there is already some handling for it in the new js htmlmaker, had a couple of questions about what & where to update.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

An addition to the task:  strip ChapNumber paras in the htmltohtmlbook.js

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Submitted PR: https://github.com/macmillanpublishers/htmlmaker_js/pull/35

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Submitted new PR: https://github.com/macmillanpublishers/htmlmaker_js/pull/36
