### ISSUE TITLE
[ss] Revise page break handling

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker#168]
Page break paras should be preserved under the new section start rules.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

this is currently happening in the xsl, we should verify this will not happen with js (check omitparas group in style_config.json)

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Verified that Page break paras are preserved in the new htmlmaker_js toolchain – it is not in the omitparas list, and a test PB para was not stripped in a test conversion.
