### ISSUE TITLE
[ss] Revise TOC handling

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker#169]
Trigger manual TOC display based on the new section-contents style

**Comment by mattretzer** [comment]
(If Section-Contents exists, trigger manual TOC display)

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Submitted 3 PRs for review, the other 2 are linked/referenced from this one: https://github.com/macmillanpublishers/bookmaker/pull/179

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Merged into sectionstartstaging branch in bookmaker & bookmaker_Addons!
