### ISSUE TITLE
[ss] Strip blank page sections

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker#170]
Remove all section-blank sections entirely.

NB: We do want these to get converted in the first part of the new hmtlmaker_js conversion. We'll then strip them out during the laster part of htmlmaker (in case they have any content, like page number placeholder, etc.)

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Add this to hrmlmaker_postprocessing.js

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Submitted PR for this: https://github.com/macmillanpublishers/bookmaker_addons/pull/152

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

The code for this small patch is now grouped with this task:  https://app.asana.com/0/290792352253123/334239063896959, moving this one to done and handling assignments etc through that task
