### ISSUE TITLE
[ss] Evaluate bandaid.js

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker#172]
Evaluate all the functions in this file and remove/revise as needed, based on the new htmlmaker_js: https://github.com/macmillanpublishers/bookmaker/blob/master/core/htmlmaker/bandaid.js

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Submitted 2 PRs for this: https://github.com/macmillanpublishers/bookmaker_addons/pull/152 and https://github.com/macmillanpublishers/bookmaker/pull/182

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

The code for this patch is now grouped with this task:  https://app.asana.com/0/290792352253123/334239063896959, moving this one to done and handling assignments etc through that task
