### ISSUE TITLE
[ss] Delete footnotes.js

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker#173]
This file will no longer be necessary when we roll out htmlmaker_js: https://github.com/macmillanpublishers/bookmaker/blob/master/core/htmlmaker/footnotes.js

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

this has been merged into the bookmaker "sectionstartstaging" branch via PR 176
