### ISSUE TITLE
[ss] Rework headings.js to pull from header element first

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker#174]
Rework the headings.js h1 creation so that if there is no direct h1 child present, to pull the Nonprinting h1 from the header element first before trying to create one from scratch.

Additionally, the class functions at the end (adding classes for abouttheauthor etc) will no longer be necessary and should be removed.

https://github.com/macmillanpublishers/bookmaker/blob/master/core/htmlmaker/headings.js

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

submitted PR for this: https://github.com/macmillanpublishers/bookmaker/pull/180

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

This is merged into sectionstartstaging branch, moving to 'Done'
