### ISSUE TITLE
[ss] Delete lists.js

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker#175]
This file will no longer be necessary when we roll out the new htmlmaker_js conversions: https://github.com/macmillanpublishers/bookmaker/blob/master/core/htmlmaker/lists.js

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Combined bookmaker issue 171, 173, 175 in this PR submitted for review: https://github.com/macmillanpublishers/bookmaker/pull/176

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

this has been merged into the bookmaker "sectionstartstaging" branch
