### ISSUE TITLE
Review htmlmaker.rb prior to flipping the switch to HTML creation via JS

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker#181]
We can use the version in the sectionstartstaging branch as a jumping off point: https://github.com/macmillanpublishers/bookmaker/blob/sectionstartstaging/core/htmlmaker/htmlmaker.rb

**Comment by MacmillanWorkflows** [comment]
➤ 9491251705208 commented:

This is included in these PRs:
https://github.com/macmillanpublishers/bookmaker/pull/185
https://github.com/macmillanpublishers/bookmaker_addons/pull/158

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

merged into sectionstartstaging
