### ISSUE TITLE
[4] One file causing node.js hang in sectionstartstaging version of htmlmaker.rb

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker#198]
https://www.dropbox.com/s/qik5b5es96lssup/9781250175489_MNU.docx?dl=0

Seems like a loop or something. We should investigate so we can help it fail gracefully.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Assigning to Luigi for review:
https://github.com/macmillanpublishers/htmlmaker_js/pull/71

**Comment by MacmillanWorkflows** [comment]
➤ luigi.squillante commented:

approved

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

merged
