### ISSUE TITLE
[epubmaker] Strip content from space break paras

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker#25]
Kindle doesn't allow content overrides (content: " ";), so we'll need to strip any content from space break paragraphs before conversion.

This should be fairly straight forward: we need to strip out the text node content of the following paragraph types:

p.SpaceBreak
p.SpaceBreak-1-Linels1
p.SpaceBreak-2-Linels2
p.SpaceBreak-3-Linels3
p.SpaceBreakOrnamentorn
p.SpaceBreakwithOrnamentorn
p.SpaceBreakwithALTOrnamentorn2

This can be done either via XSL or ruby, for epubmaker only.

**Comment by nelliemckesson** [comment]
ACTUALLY we need to inject content into every space break paragraph, for EPUBs only. We need to replace the text node content for every space break with "* * *" (3 asterisks, separated by spaces). This includes both blank and ORN space break styles. You'll also need to search for paragraphs that have both an opening and closing tag (<p></p>) as well as self-closing paragraphs (<p />).

**Comment by mattretzer** [comment]
Added gsubs to epub preprocessing.rb to resolve.  Tested, merged, all set.
