### ISSUE TITLE
Make all system paths configurable

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker#92]
Instead of requiring dependencies to be installed in the same folder, make all dependency commands configurable in the config file. Then in header.rb, use that config var if it exists, else fall back to standard shortcut commands (e.g., "ruby ...").

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

I think Nellie did this with the bookmaker cfg file. Closing
